add as_rtf for gsBinomialExactTable
keaven/gsDesign pull request #102
Opened 2023-08-21 01:29 UTC by wangben718

write as_rtf method for gsBinomialExactTable

2023-08-22 01:33 UTC, LittleBeannie commented on R/as_rtf.R
> +           en_label = "Expected sample sizes",
I added another input called `en_label=...`, and please make sure to update the functions in the subsequent flow.

2023-08-22 01:34 UTC, LittleBeannie commented on R/as_rtf.R
> +           title = "Operating Characteristics for the Truncated SPRT Design",
Could you please list me the reference of the default title and subtitle? I can help ask Keaven to check if he gets any preference for the defaults.

2023-08-22 05:22 UTC, nanxstats requested changes
Please see my comments above.

2023-08-22 05:22 UTC, nanxstats commented on DESCRIPTION
> +    r2rtf
Maybe this is not too obvious but the dependencies should be listed in alphabetical orders.

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' Print a summary table using gt
I thought this is RTF, not gt.

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' Create RTF file created with \code{\link{as_table}} to summarize
Avoid using two consecutive "create".

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @param x   Object to be display on rtf.
Use only one whitespace between param name and description.

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @param x   Object to be display on rtf.
I would rewrite the description. "Object to be display(ed) on rtf" sounds off.

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @param ... Other parameters that may be specific the object.
What does "that may be specific the object" mean?

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @return NULL.
You should return the input object invisibly. See tidyverse design guide: https://design.tidyverse.org/out-invisible.html

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @examples
If you have the `@examples` section, it should have code examples and not left blank.

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @param en_label Label for en.
It's unclear to me what "en" means - you should make it clear.

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +#' @param rtf_path Output path for the rtf file.
I'd name this argument `file` and keep it consistent across all such functions.

```r
#' @param file File path for the output.
```

2023-08-22 05:22 UTC, nanxstats commented on R/as_rtf.R
> +    x[,2] <- sprintf(paste0("%.", prob_decimals,"f"), unlist(x[,2]))
I'm not sure if it's possible here but we should strive to access data frame or list elements by their names, not the index number.

2023-09-11 18:10 UTC, LittleBeannie commented on R/as_rtf.R
> +#' @param response_outcome Is outcome response rate
Can we refine the explanation of `response_outcome` as `Logical values indicating if the outcome is response rate (TRUE) or failure rate (FALSE).

2023-09-11 19:37 UTC, LittleBeannie approved these changes

2023-10-09 16:03 UTC, nanxstats commented on R/as_rtf.R
> +#' @return NULL.
Note that the returned object should be the **original input**, not the modified object.

2023-10-10 04:36 UTC, nanxstats commented
I updated the code to remove the check note on `title` \usage more than 90 characters wide and improved the general code and documentation style in both `as_rtf()` and `as_gt()`.

Most importantly, I now put `...` right after required arguments following the [tidyverse design guide](https://design.tidyverse.org/dots-after-required.html) to avoid potential coding pitfalls for users.

I just have some final minor questions regarding the RTF output style and consistency generated by the example code:

1. In the first output, the second "Probability of crossing" column has NA as the sub-column name.
2. In the second output, the two columns are named "low rate" and "high rate" - should they use sentence case as the other columns?
3. In both outputs, should column names use sentence case or title case?
4. In both outputs, should table title use sentence case or title case?

2023-10-11 13:51 UTC, nanxstats commented
Thanks for improving the details in the output tables. It turns out for a length-1 input, `ifelse()` (as designed) returns only the first value, so using `if else` instead is the proper way.

2023-10-11 13:55 UTC, merged